app/symfony/src/Entity/Order.php
<?php

namespace App\Entity;

use App\Entity\Traits\IdentifiableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\Table(name="orders")
 * @Serializer\ExclusionPolicy("all")
 */
class Order
{
    use IdentifiableTrait;

    const STATUS_REGISTERED = 'registered';
    const STATUS_CONFIRMED = 'confirmed';
    const STATUS_CANCELLED = 'cancelled';
    const STATUS_WAITING = 'waiting';
    const STATUS_REFUNDED = 'refunded';
    const STATUS_PENDING = 'pending';

    /**
     * @var Course
     * @ORM\ManyToOne(targetEntity=Course::class, inversedBy="orders", cascade={"persist"})
     * @Serializer\Expose()
     */
    protected $course;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity=Export::class, cascade={"persist"})
     */
    protected $exports;

    /**
     * @var string
     * @ORM\Column()
     */
    protected $status = self::STATUS_PENDING;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $commission;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $refundedAmount;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $discountAmount;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $optionsAmount;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     * @Serializer\Expose()
     */
    protected $fee;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $letter;

    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     * @Serializer\Expose()
     */
    protected $paidAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    protected $confirmedAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    protected $cancelledAt;

    /**
     * @var string
     * @ORM\Column(nullable=true)
     */
    protected $reference;

    /**
     * @var string
     * @ORM\Column(nullable=true)
     */
    protected $reason;

    /**
     * @var Trainee
     * @ORM\OneToOne(targetEntity=Trainee::class, cascade={"persist"})
     * @Serializer\Expose()
     */
    protected $trainee;

    /**
     * @var Option[]
     * @ORM\ManyToMany(targetEntity=Option::class, cascade={"persist"})
     * @Serializer\Expose()
     */
    protected $options;

    /**
     * @var Coupon
     * @ORM\ManyToOne(targetEntity=Coupon::class, cascade={"persist"})
     */
    protected $coupon;

    /**
     * @var float
     * @ORM\Column(type="float", nullable=true)
     */
    protected $amount;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="order", cascade={"persist"})
     */
    protected $transactions;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $reducedCommission = false;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $refundAt;

    public function __construct()
    {
        $this->options = new ArrayCollection();
        $this->transactions = new ArrayCollection();
        $this->exports = new ArrayCollection();
    }

    /**
     * @param Option $option
     */
    public function addOption(Option $option): void
    {
        if ($this->options->contains($option)) {
            return;
        }

        $this->options->add($option);
    }

    /**
     * @param Option $option
     */
    public function removeOption(Option $option)
    {
        if (!$this->options->contains($option)) {
            return;
        }

        $this->options->removeElement($option);
    }

    /**
     * @param Option $option
     *
     * @return bool
     */
    public function hasOption(Option $option): bool
    {
        return $this->options->contains($option);
    }

    /**
     * @return Collection
     */
    public function getOptions(): ?Collection
    {
        return $this->options;
    }

    /**
     * @return Coupon
     */
    public function getCoupon(): ?Coupon
    {
        return $this->coupon;
    }

    /**
     * @param Coupon $coupon
     */
    public function setCoupon(?Coupon $coupon): void
    {
        $this->coupon = $coupon;
    }

    /**
     * @return string
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus($status): void
    {
        $this->status = $status;
    }

    /**
     * @return string
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * @param string $reference
     */
    public function setReference($reference): void
    {
        $this->reference = $reference;
    }

    /**
     * @return string
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * @param string $reason
     */
    public function setReason($reason): void
    {
        $this->reason = $reason;
    }

    /**
     * @return Trainee
     */
    public function getTrainee(): ?Trainee
    {
        return $this->trainee;
    }

    /**
     * @param Trainee $trainee
     */
    public function setTrainee(Trainee $trainee): void
    {
        $this->trainee = $trainee;
    }

    /**
     * @return Course
     */
    public function getCourse(): ?Course
    {
        return $this->course;
    }

    /**
     * @param Course $course
     */
    public function setCourse(Course $course): void
    {
        $this->course = $course;
    }

    /**
     * @return \DateTime
     */
    public function getPaidAt(): ?\DateTime
    {
        return $this->paidAt;
    }

    /**
     * @param \DateTime $paidAt
     */
    public function setPaidAt(\DateTime $paidAt): void
    {
        $this->paidAt = $paidAt;
    }

    /**
     * @return \DateTime
     */
    public function getConfirmedAt(): ?\DateTime
    {
        return $this->confirmedAt;
    }

    /**
     * @param \DateTime $confirmedAt
     */
    public function setConfirmedAt(\DateTime $confirmedAt): void
    {
        $this->confirmedAt = $confirmedAt;
    }

    /**
     * @return float
     */
    public function getRefundedAmount(): ?float
    {
        return $this->refundedAmount;
    }

    /**
     * @param float $refundedAmount
     */
    public function setRefundedAmount(?float $refundedAmount): void
    {
        $this->refundedAmount = $refundedAmount;
    }

    /**
     * @return float
     */
    public function getDiscountAmount(): ?float
    {
        return $this->discountAmount;
    }

    /**
     * @param float $discountAmount
     */
    public function setDiscountAmount(?float $discountAmount): void
    {
        $this->discountAmount = $discountAmount;
    }

    /**
     * @return float
     */
    public function getOptionsAmount(): ?float
    {
        return $this->optionsAmount;
    }

    /**
     * @param float $optionsAmount
     */
    public function setOptionsAmount(?float $optionsAmount): void
    {
        $this->optionsAmount = $optionsAmount;
    }

    /**
     * @return float
     */
    public function getFee(): ?float
    {
        return $this->fee;
    }

    /**
     * @param float $fee
     */
    public function setFee(?float $fee): void
    {
        $this->fee = $fee;
    }

    /**
     * @return float
     */
    public function getLetter(): ?float
    {
        return $this->letter;
    }

    /**
     * @param float $letter
     */
    public function setLetter(?float $letter): void
    {
        $this->letter = $letter;
    }

    /**
     * @return \DateTime
     */
    public function getCancelledAt(): ?\DateTime
    {
        return $this->cancelledAt;
    }

    /**
     * @param \DateTime $cancelledAt
     */
    public function setCancelledAt(\DateTime $cancelledAt): void
    {
        $this->cancelledAt = $cancelledAt;
    }

    /**
     * @return float
     */
    public function getCommission(): ?float
    {
        return $this->commission;
    }

    /**
     * @param float $commission
     */
    public function setCommission(float $commission): void
    {
        $this->commission = $commission;
    }

    /**
     * @return float
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * @param float $amount
     */
    public function setAmount(?float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * return float.
     */
    public function getAmountWithoutOptions()
    {
        $amount = $this->amount;

        $amount -= $this->optionsAmount;
        $amount += $this->discountAmount;

        return $amount;
    }

    /**
     * @param Transaction $transaction
     */
    public function addTransaction(Transaction $transaction)
    {
        if ($this->transactions->contains($transaction)) {
            return;
        }

        $this->transactions->add($transaction);
    }

    /**
     * @return Collection
     */
    public function getTransactions(): ?Collection
    {
        return $this->transactions;
    }

    /**
     * @return bool
     */
    public function isReducedCommission(): bool
    {
        return $this->reducedCommission;
    }

    /**
     * @param bool $reducedCommission
     */
    public function setReducedCommission(bool $reducedCommission): void
    {
        $this->reducedCommission = $reducedCommission;
    }

    /**
     * @return \DateTime
     */
    public function getRefundAt(): \DateTime
    {
        return $this->refundAt;
    }

    /**
     * @param \DateTime $refundAt
     */

app/symfony/src/Controller/Middle/AccountingController.php
<?php

namespace App\Controller\Middle;

use App\Entity\Center;
use App\Services\ReportingService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;

class AccountingController extends AbstractController
{
    /**
     * @Route(path="/cssr/accounting", name="middle_accounting_list", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_VIEW'))")
     *
     * @return Response
     */
    public function list(): Response
    {
        return $this->render('middle/accounting/list.html.twig');
    }

    /**
     * @Route(path="/cssr/accounting/fee", name="middle_accounting_fee", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_FEE'))")
     *
     * @param ReportingService $reportingService
     * @param Center|null      $center
     *
     * @return StreamedResponse
     */
    public function fee(ReportingService $reportingService): Response
    {
        return $reportingService->exportApplicationFee();
    }

    /**
     * @Route(path="/cssr/accounting/refund", name="middle_accounting_refund", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_REFUND'))")
     *
     * @param ReportingService $reportingService
     * @param Center           $center
     *
     * @return StreamedResponse
     */
    public function refund(ReportingService $reportingService): Response
    {
        return $reportingService->exportOrderRefund();
    }

    /**
     * @Route(path="/cssr/accounting/banking", name="middle_accounting_banking", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_BANKING'))")
     *
     * @param ReportingService $reportingService
     *
     * @return Response
     */
    public function banking(ReportingService $reportingService): Response
    {
        $export = $reportingService->getExportBankZip();

        $response = new Response(file_get_contents($export));
        $response->headers->set('Content-Type', 'text/csv; charset=windows-1252');
        $response->headers->set('Content-Type', 'application/zip');
        $response->headers->set('Content-Disposition', 'attachment;filename="'.$export.'"');
        $response->headers->set('Content-length', filesize($export));

        unlink($export);

        return $response;
    }
}

app/symfony/src/Controller/Middle/AnimatorController.php
<?php

namespace App\Controller\Middle;

use App\Entity\Animator;
use App\Form\AnimatorType;
use App\Form\Search\AnimatorSearchType;
use App\Manager\AnimatorManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

class AnimatorController extends AbstractController
{
    /**
     * @Route("/cssr/animators", name="middle_animators", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AnimatorVoter::ANIMATOR_LIST'))")
     *
     * @param Request         $request
     * @param AnimatorManager $animatorManager
     *
     * @return Response
     */
    public function list(
        Request $request,
        AnimatorManager $animatorManager
    ): Response {
        $form = $this->createForm(AnimatorSearchType::class, null);

        $form->handleRequest($request);
        $filters = $form->getData();

        return $this->render('middle/animator/list.html.twig', [
            'animators' => $animatorManager->collect($this->getUser(), $filters),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/cssr/animator", name="middle_animator_create", methods={"GET","POST"})
     * @Route("/cssr/animator/{id}/edit", name="middle_animator_edit", methods={"GET","POST"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AnimatorVoter::ANIMATOR_EDIT'))")
     *
     * @param Request         $request
     * @param Animator|null   $animator
     * @param AnimatorManager $animatorManager
     *
     * @return Response
     */
    public function edit(
        Request $request,
        ?Animator $animator,
        AnimatorManager $animatorManager
    ): Response {
        if (!$animator instanceof Animator) {
            $animator = new Animator();
        }

        $form = $this->createForm(AnimatorType::class, $animator, [
            'user' => $this->getUser(),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($animator->getId()) {
                $animatorManager->update();
            } else {
                $animatorManager->create($animator, $this->getUser());
            }

            return $this->redirectToRoute('middle_animators');
        }

        return $this->render('middle/animator/edit.html.twig', [
            'animator' => $animator,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/cssr/animator/{id}", name="animator_delete", methods={"DELETE"})
     *
     * @param Animator            $animator
     * @param AnimatorManager     $animatorManager
     * @param TranslatorInterface $translator
     *
     * @return Response
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AnimatorVoter::ANIMATOR_DELETE'))")
     */
    public function delete(
        Animator $animator,
        AnimatorManager $animatorManager,
        TranslatorInterface $translator
    ): Response {
        $animatorManager->delete($animator);

        return new JsonResponse($translator->trans('message.flash.animatorDelete'));
    }
}

app/symfony/src/Controller/Middle/ConditionController.php
<?php

namespace App\Controller\Middle;

use App\Manager\CenterManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;

class ConditionController extends AbstractController
{
    /**
     * @Route("/cssr/condition/validate", name="middle_condition_validate", methods={"POST"})
     *
     * @param CenterManager $centerManager
     *
     * @return RedirectResponse
     */
    public function validate(CenterManager $centerManager): RedirectResponse
    {
        $user = $this->getUser();

        $centerManager->validationCondition($user->getCenter());

        return $this->redirectToRoute('dashboard');
    }
}

app/symfony/templates/middle/order/_refund.html.twig
{{ form_start(form, { attr: { action: path('api_order_refund', { id: order.id }) }}) }}
  <div class="row">
    <div class="col-12">
      <p><u>{{ 'info.modal.rembouser_stagiaire'|trans }} </u>: {{ order.trainee }}</p>
      <p>{{ 'info.modal.montant_stage'|trans }} : {{ order.amountWithoutOptions }} €</p>
      <p>{{ 'info.modal.montant_frais'|trans }} : {{ order.fee }} €</p>
      <p>{{ 'info.modal.send_letter'|trans }} : {{ order.letter }} €</p>
      <p>{{ 'info.modal.order_paid'|trans }} : {{ order.paidAt|date('Y.m.d') }}</p>
      <p>{{ 'info.modal.jour_stage'|trans }} : {{ order.course.startOn|date('Y.m.d') }}</p>
      {{ form_row(form.refundedAmount) }}
      {{ form_row(form.reason) }}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="modal-actions">
        {{ form_row(form.submit, { attr: { id: 'modal-order-refund', class: 'btn-secondary btn-sm' } }) }}
      </div>
    </div>
  </div>
{{ form_end(form) }}

app/symfony/templates/middle/order/index.html.twig
{% extends 'middle/base.html.twig' %}

{% block body %}
<div class="intern-card-wrap d-print-block">
  <div class="middle-title-section">
    <h1 class="middle-default-title"> {{ 'info.order.titleIndex'|trans }} </h1>
    <div class="head-action-block d-print-none">
      <ul class="list-middle-link list-inline float-left">
        <li class="list-inline-item"><a href="javascript:void(0)" onclick="window.print();">{{ 'info.order.imprimer'|trans }}</a></li>
        <li class="list-inline-item"><a href="{{ path('middle_order_convocation', { 'id': order.id }) }}" target="_blank">{{ 'info.order.voirConvocation'|trans }}</a></li>
        {% if is_granted(constant('App\\Security\\Voter\\TraineeVoter::TRAINEE_EDIT'), order.trainee) %}
          <li class="list-inline-item"><a href="{{ path('middle_trainee_edit', { id: order.trainee.id }) }}">{{ 'form.action.edit'|trans }}</a></li>
        {% endif %}
       </ul>
    </div>
  </div>

  <div class="detail-intern-wrap">
    <div class="row">
      <!-- Coordonnees -->
      <div class="col-sm-4">
        <div class="detail-default-block">
          <h3 class="detail-default-title">{{ 'info.order.coordonnee'|trans }} </h3>
          <ul class="list-info-default list-xs list-unstyled">
            <li>
              <div class="info-label">{{ 'info.order.ref'|trans }} :</div>
              <div class="info-detail info-mail">{{ order.trainee.reference }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.nom'|trans }}  :</div>
              <div class="info-detail info-mail">{{ order.trainee.lastName }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.prenom'|trans }}  :</div>
              <div class="info-detail info-mail">{{ order.trainee.firstName }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.adresse'|trans }}  :</div>
              <div class="info-detail">{{ order.trainee.address }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.codePostal'|trans }} :</div>
              <div class="info-detail">{{ order.trainee.postalCode }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.ville'|trans }}  :</div>
              <div class="info-detail">{{ order.trainee.city }}</div>
            </li>
            {% if order.trainee.email is not same as(constant('App\\Entity\\Parameter::EMAIL_DEFAULT')) %}
              <li>
                <div class="info-label">{{ 'info.order.email'|trans }}  :</div>
                <div class="info-detail info-mail">{{ order.trainee.email }}</div>
              </li>
            {% endif %}
            <li>
              <div class="info-label">{{ 'info.trainee.phone'|trans }}  :</div>
              <div class="info-detail info-mail">{{ order.trainee.phone }}</div>
            </li>
          </ul>
        </div>
      </div>

      <!-- Commande -->
      <div class="col-sm-4">
        <div class="detail-default-block">
          <h3 class="detail-default-title">{{ 'info.order.commande'|trans }}</h3>
          <ul class="list-info-default list-unstyled">
            <li>
              <div class="info-label">{{ 'info.order.status'|trans }} :</div>
              <div class="info-detail">{{ ('info.order.state.' ~ order.status)|trans }}</div>
            </li>
            {% if order.trainee.reference %}
              <li>
                <div class="info-label">{{ 'info.order.numeroFacture'|trans }} :</div>
                <div class="info-detail">{{ order.reference }}</div>
              </li>
              <li>
                <div class="info-label">{{ 'info.order.montantPaye'|trans }} :</div>
                <div class="info-detail">{{ order.course.amount }} &euro; </div>
              </li>
              <li>
                <div class="info-label">{{ 'info.order.dateAchat'|trans }} :</div>
                <div class="info-detail">{{ order.paidAt|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy")|capitalize }}</div>
              </li>
            {% endif %}
            <li>
              <div class="info-label">{{ 'info.order.dateConfirmationStage'|trans }} : </div>
              <div class="info-detail">{{ order.confirmedAt|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy")|capitalize }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.nomCSSR'|trans }} : </div>
              <div class="info-detail">{{ order.course.center.name }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.jourStage'|trans }} : </div>
              <div class="info-detail">{{ order.course.startOn|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy")|capitalize }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.lieuStage'|trans }} :  </div>
              <div class="info-detail">{{ order.course.place.city }} {{ order.course.place.address }}</div>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-sm-4">
        <!-- Permis -->
        <div class="detail-default-block">
          <h3 class="detail-default-title">{{ 'info.order.permis'|trans }}</h3>
          <ul class="list-info-default list-unstyled">
            <li>
              <div class="info-label">{{ 'info.order.numeroPermis'|trans }} :</div>
              <div class="info-detail">{{ order.trainee.driverLicense }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.deliveredOn'|trans }} :</div>
              <div class="info-detail">{{ order.trainee.deliveredOn|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy")|capitalize }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.deliveredAt'|trans }} :</div>
              <div class="info-detail">{{ order.trainee.deliveredAt }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.obtainedOn'|trans }} :</div>
              <div class="info-detail">{{ order.trainee.obtainedOn|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy")|capitalize }}</div>
            </li>
            <li>
              <div class="info-label">{{ 'info.order.typeStage'|trans }} :</div>
              <div class="info-detail">{{ ('info.trainee.type.' ~ order.trainee.courseType)|trans }}</div>
            </li>
          </ul>
        </div>
        {% if order.trainee.comment is not null %}
          <div class="detail-default-block">
            <h3 class="detail-default-title">{{ 'info.order.commentaire'|trans }}</h3>
            <div class="detail-comment-text">{{ order.trainee.comment }}</div>
          </div>
        {% endif %}
        {% if order.reason is not null %}
          <div class="detail-default-block">
            <h3 class="detail-default-title">{{ 'info.order.reason'|trans }}</h3>
            <div class="detail-comment-text">{{ order.reason }}</div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}