app/symfony/src/Entity/Tarif.php
<?php

namespace App\Entity;

use App\Entity\Traits\IdentifiableTrait;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity()
 */
class Tarif
{
    const TYPE_COURSE = 'course';
    const TYPE_DATE = 'date';

    use IdentifiableTrait;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $commission;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $commissionByCourse;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $commissionByDate;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    protected $confirmedCourse = 0;

    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    protected $endOn;

    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    protected $startOn;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $totalCourse;

    /**
     * @var string
     * @ORM\Column(nullable=true)
     */
    protected $type;

    /**
     * @return int
     */
    public function getCommission(): ?float
    {
        return $this->commission;
    }

    /**
     * @param float $commission
     */
    public function setCommission(float $commission): void
    {
        $this->commission = $commission;
    }

    /**
     * @return float
     */
    public function getCommissionByCourse(): ?float
    {
        return $this->commissionByCourse;
    }

    /**
     * @param float $commissionByCourse
     */
    public function setCommissionByCourse(?float $commissionByCourse): void
    {
        $this->commissionByCourse = $commissionByCourse;
    }

    /**
     * @return float
     */
    public function getCommissionByDate(): ?float
    {
        return $this->commissionByDate;
    }

    /**
     * @param float $commissionByDate
     */
    public function setCommissionByDate(?float $commissionByDate): void
    {
        $this->commissionByDate = $commissionByDate;
    }

    /**
     * @return int
     */
    public function getConfirmedCourse(): ?int
    {
        return $this->confirmedCourse;
    }

    /**
     * @param int $confirmedCourse
     */
    public function setConfirmedCourse(int $confirmedCourse): void
    {
        $this->confirmedCourse = $confirmedCourse;
    }

    /**
     * @return \DateTime
     */
    public function getEndOn(): ?\DateTime
    {
        return $this->endOn;
    }

    /**
     * @param \DateTime $endOn
     */
    public function setEndOn(?\DateTime $endOn): void
    {
        $this->endOn = $endOn;
    }

    /**
     * @return \DateTime
     */
    public function getStartOn(): ?\DateTime
    {
        return $this->startOn;
    }

    /**
     * @param \DateTime $startOn
     */
    public function setStartOn(?\DateTime $startOn): void
    {
        $this->startOn = $startOn;
    }

    /**
     * @return int
     */
    public function getTotalCourse(): ?int
    {
        return $this->totalCourse;
    }

    /**
     * @param int $totalCourse
     */
    public function setTotalCourse(?int $totalCourse): void
    {
        $this->totalCourse = $totalCourse;
    }

    /**
     * @return string
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * @return int
     */
    public function getRemainingCourse(): ?int
    {
        return $this->totalCourse - $this->confirmedCourse;
    }

    /**
     * @return bool
     */
    public function isDiscountDateActive(): ?bool
    {
        return $this->startOn <= new \DateTime(date('Y-m-d')) && $this->endOn >= new \DateTime(date('Y-m-d'));
    }

    /**
     * @param ExecutionContextInterface $context
     * @param $payload
     * @Assert\Callback()
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if ($this->startOn >= $this->endOn) {
            $context
                ->buildViolation('validator.date.endOn')
                ->atPath('endOn')
                ->addViolation()
            ;
        }

        if ($this->startOn <= new \DateTime('now')) {
            $context
                ->buildViolation('validator.date.startOn')
                ->atPath('startOn')
                ->addViolation()
            ;
        }
    }
}

app/symfony/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Page;
use App\Entity\Submission;
use App\Form\SearchType;
use App\Form\SubmissionType;
use App\Manager\FaqManager;
use App\Manager\OrderManager;
use App\Manager\PageManager;
use App\Manager\SubmissionManager;
use App\Manager\TestimonialManager;
use App\Services\MessageService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

class DefaultController extends AbstractController
{
    /**
     * @Route(path="/", name="homepage", methods={"GET"})
     *
     * @param TestimonialManager $testimonialManager
     * @param Session            $session
     * @param OrderManager       $orderManager
     *
     * @return Response
     */
    public function index(TestimonialManager $testimonialManager, OrderManager $orderManager, Session $session): Response
    {
        $form = $this->createForm(SearchType::class);

        $orderManager->clear($session);

        return $this->render('front/default/index.html.twig', [
            'testimonials' => $testimonialManager->collect(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route(path="/contact", name="contact")
     *
     * @param Request             $request
     * @param SubmissionManager   $submissionManager
     * @param TranslatorInterface $translator
     *
     * @return Response
     */
    public function contact(
        Request $request,
        SubmissionManager $submissionManager,
        TranslatorInterface $translator
    ): Response {
        $submission = new Submission();

        $form = $this->createForm(SubmissionType::class, $submission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $submissionManager->create($submission);
            // @TODO: MessageService implementation
            $this->addFlash(
                'notice',
                $translator->trans('message.flash.submissionOk')
            );

            return $this->redirectToRoute('contact');
        }

        return $this->render('front/default/submission.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route(path="/faq", name="faq")
     *
     * @param FaqManager $faqManager
     *
     * @return Response
     */
    public function faq(FaqManager $faqManager): Response
    {
        return $this->render('front/default/faq.html.twig', [
            'faqs' => $faqManager->collect(),
        ]);
    }

    /**
     * @Route(path="/page/{slug}", name="page", methods={"GET"})
     *
     * @param Page $page
     *
     * @return Response
     */
    public function page(Page $page): Response
    {
        return $this->render('front/default/page.html.twig', [
            'page' => $page,
        ]);
    }

    /**
     * @Route(path="/sitemap.{_format}", defaults={"_format"="xml"}, name="sitemap", methods={"GET"})
     *
     * @param PageRepository $pageRepository
     *
     * @return Response
     */
    public function sitemap(
        Request $request,
        PageManager $pageManager
    ): Response {
        return $this->render('front/default/sitemap.xml.twig', [
            'pages' => $pageManager->collect(),
        ]);
    }
}

app/symfony/src/Controller/Middle/AccountingController.php
<?php

namespace App\Controller\Middle;

use App\Entity\Center;
use App\Services\ReportingService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;

class AccountingController extends AbstractController
{
    /**
     * @Route(path="/cssr/accounting", name="middle_accounting_list", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_VIEW'))")
     *
     * @return Response
     */
    public function list(): Response
    {
        return $this->render('middle/accounting/list.html.twig');
    }

    /**
     * @Route(path="/cssr/accounting/fee", name="middle_accounting_fee", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_FEE'))")
     *
     * @param ReportingService $reportingService
     * @param Center|null      $center
     *
     * @return StreamedResponse
     */
    public function fee(ReportingService $reportingService): Response
    {
        return $reportingService->exportApplicationFee();
    }

    /**
     * @Route(path="/cssr/accounting/refund", name="middle_accounting_refund", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_REFUND'))")
     *
     * @param ReportingService $reportingService
     * @param Center           $center
     *
     * @return StreamedResponse
     */
    public function refund(ReportingService $reportingService): Response
    {
        return $reportingService->exportOrderRefund();
    }

    /**
     * @Route(path="/cssr/accounting/banking", name="middle_accounting_banking", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_BANKING'))")
     *
     * @param ReportingService $reportingService
     *
     * @return Response
     */
    public function banking(ReportingService $reportingService): Response
    {
        $export = $reportingService->getExportBankZip();

        $response = new Response(file_get_contents($export));
        $response->headers->set('Content-Type', 'text/csv; charset=windows-1252');
        $response->headers->set('Content-Type', 'application/zip');
        $response->headers->set('Content-Disposition', 'attachment;filename="'.$export.'"');
        $response->headers->set('Content-length', filesize($export));

        unlink($export);

        return $response;
    }
}

app/symfony/src/Controller/Middle/AnimatorController.php
<?php

namespace App\Controller\Middle;

use App\Entity\Animator;
use App\Form\AnimatorType;
use App\Form\Search\AnimatorSearchType;
use App\Manager\AnimatorManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

class AnimatorController extends AbstractController
{
    /**
     * @Route("/cssr/animators", name="middle_animators", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AnimatorVoter::ANIMATOR_LIST'))")
     *
     * @param Request         $request
     * @param AnimatorManager $animatorManager
     *
     * @return Response
     */
    public function list(
        Request $request,
        AnimatorManager $animatorManager
    ): Response {
        $form = $this->createForm(AnimatorSearchType::class, null);

        $form->handleRequest($request);
        $filters = $form->getData();

        return $this->render('middle/animator/list.html.twig', [
            'animators' => $animatorManager->collect($this->getUser(), $filters),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/cssr/animator", name="middle_animator_create", methods={"GET","POST"})
     * @Route("/cssr/animator/{id}/edit", name="middle_animator_edit", methods={"GET","POST"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AnimatorVoter::ANIMATOR_EDIT'))")
     *
     * @param Request         $request
     * @param Animator|null   $animator
     * @param AnimatorManager $animatorManager
     *
     * @return Response
     */
    public function edit(
        Request $request,
        ?Animator $animator,
        AnimatorManager $animatorManager
    ): Response {
        if (!$animator instanceof Animator) {
            $animator = new Animator();
        }

        $form = $this->createForm(AnimatorType::class, $animator, [
            'user' => $this->getUser(),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($animator->getId()) {
                $animatorManager->update();
            } else {
                $animatorManager->create($animator, $this->getUser());
            }

            return $this->redirectToRoute('middle_animators');
        }

        return $this->render('middle/animator/edit.html.twig', [
            'animator' => $animator,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/cssr/animator/{id}", name="animator_delete", methods={"DELETE"})
     *
     * @param Animator            $animator
     * @param AnimatorManager     $animatorManager
     * @param TranslatorInterface $translator
     *
     * @return Response
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AnimatorVoter::ANIMATOR_DELETE'))")
     */
    public function delete(
        Animator $animator,
        AnimatorManager $animatorManager,
        TranslatorInterface $translator
    ): Response {
        $animatorManager->delete($animator);

        return new JsonResponse($translator->trans('message.flash.animatorDelete'));
    }
}

app/symfony/src/Controller/Middle/ConditionController.php
<?php

namespace App\Controller\Middle;

use App\Manager\CenterManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;

class ConditionController extends AbstractController
{
    /**
     * @Route("/cssr/condition/validate", name="middle_condition_validate", methods={"POST"})
     *
     * @param CenterManager $centerManager
     *
     * @return RedirectResponse
     */
    public function validate(CenterManager $centerManager): RedirectResponse
    {
        $user = $this->getUser();

        $centerManager->validationCondition($user->getCenter());

        return $this->redirectToRoute('dashboard');
    }
}

app/symfony/src/Controller/Middle/DefaultController.php
<?php

namespace App\Controller\Middle;

use App\Entity\User;
use App\Manager\CourseManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class DefaultController extends AbstractController
{
    /**
     * @Route(path="/cssr", name="dashboard", methods={"GET"})
     *
     * @param CourseManager $courseManager
     *
     * @return Response
     */
    public function dashboard(UrlGeneratorInterface $urlG, CourseManager $courseManager): Response
    {
        $user = $this->getUser();
        $courses = null;

        if (User::ROLE_CSSR === $user->getRole()) {
            $courses = $courseManager->collectByCenter(
                $this->getUser()->getCenter(),
                null,
                2,
                false
            );
        }

        return $this->render('middle/default/index.html.twig', [
            'courses' => $courses,
        ]);
    }
}

app/symfony/src/Controller/Middle/TraineeController.php
<?php

namespace App\Controller\Middle;

use App\Entity\Trainee;
use App\Form\TraineeType;
use App\Manager\TraineeManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TraineeController extends AbstractController
{
    /**
     * @Route(path="/src/trainee/{id}", name="middle_trainee_edit", methods={"GET", "POST"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\TraineeVoter::TRAINEE_EDIT'), trainee)")
     *
     * @param Request        $request
     * @param Trainee        $trainee
     * @param TraineeManager $traineeManager
     *
     * @return Response
     */
    public function edit(
        Request $request,
        Trainee $trainee,
        TraineeManager $traineeManager
    ): Response {
        $form = $this->createForm(TraineeType::class, $trainee, ['user' => $this->getUser()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $traineeManager->update();

            return $this->redirectToRoute('middle_order', ['id' => $trainee->getOrder()->getId()]);
        }

        return $this->render('middle/trainee/edit.html.twig', [
            'trainee' => $trainee,
            'form' => $form->createView(),
        ]);
    }
}

app/symfony/templates/middle/default/index.html.twig
{% extends 'middle/base.html.twig' %}

{% block body %}

<div class="dashboard-wrap ">
  <!-- Dashbord SMP  -->
  {% if not is_granted('ROLE_CSSR') %}
  <div class=" ">
    <div class="middle-title-section">
      <h1 class="middle-default-title"> Tableau de bord </h1>
    </div>

    <table class="table table-listing table-dashboard ">
      <thead>
        <tr>
          <th></th>
          <th>Ce jour</th>
          {% if is_granted('ROLE_SMP') %}
            <th>J-1</th>
            <th>M-1</th>
            <th>M-2</th>
            <th>N-1</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
      {% for statType in constant('\\App\\Entity\\Statistical::TYPES')  %}
        <tr>
          <td>
              {{ ('stats.row.' ~ statType)|trans|raw }}
          </td>
          <td>{{ getStats(statType, null) }}</td>
            {% if is_granted('ROLE_SMP') %}
              <td>{{ getStats(statType, "-1days"|date('Y-m-d')) }}</td>
              <td>{{ getStats(statType, "-1months"|date('Y-m-d')) }}</td>
              <td>{{ getStats(statType, "-2months"|date('Y-m-d')) }}</td>
              <td>{{ getStats(statType, "-1years"|date('Y-m-d')) }}</td>
            {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <!-- Dashbord CSSR  -->
  <div class="dashboard-section">
    <div class="row">
      <div class="col-lg-6">
        <!-- Welcome -->
        <div class="dashboard-block dashboard-welcome-block">
          <h2 class="dashboard-welcome-title">
              {{ 'info.dashboard.welcome'|trans }}
            <strong>Mme/Mr {{ app.user.center.firstName }} {{ app.user.center.lastName }}</strong>
          </h2>
          <ul class="list-info-default list-xs list-unstyled">
            <li>
              <div class="info-label">Société : </div>
              <div class="info-detail">{{ app.user.center.name }}</div>
            </li>
            <li>
              <div class="info-label">Référence : </div>
              <div class="info-detail">{{ app.user.center.code }}</div>
            </li>
          </ul>
          <a href="{{ path('middle_center_edit', { id: app.user.center.id }) }}" class="link-dashboard">Modifier</a>
        </div>

        <!-- Prochaines sessions -->
        {% if courses|length %}
          <div class="dashboard-block dashboard-contact-info-block" id="course-list">
            <div class="dashboard-title-block">
              <h2 class="dashboard-title"> {{ 'info.dashboard.course'|trans }} </h2>
              <a href="{{ path('middle_courses') }}" class="link-dashboard">Voir les sessions</a>
            </div>
            <ul class="list-course list-unstyled">
              {% for course in courses %}
                <li>
                  <button type="button" class="btn btn-inscription {% if countRegistered(course, constant('\\App\\Entity\\Order::STATUS_REGISTERED')) > 0 %}pre-inscrit{% else %}no-pointer{% endif %}" data-url-register="{{ path('api_course_orders', {'id': course.id}) }}" data-course-id="{{ course.id }}">
                    <div class="session-title">
                      {{ course.place.address }}
                    </div>
                    <div class="session-date">
                        {{ course.startOn|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy")|capitalize }}
                    </div>
                    <ul class="list-session-info list-inline">
                      <li class="list-inline-item"><strong>Tarif :</strong> {{ course.amount }} €</li>
                      <li class="list-inline-item">&nbsp;</li>
                      <li class="list-inline-item"><strong>Pré-inscrit :</strong> {{ countRegistered(course, constant('\\App\\Entity\\Order::STATUS_REGISTERED')) }}</li>
                      <li class="list-inline-item"><strong>Confirmés :</strong> {{ countConfirmed(course, constant('\\App\\Entity\\Order::STATUS_CONFIRMED')) }}</li>
                    </ul>
                    <div class="session-indicator-block">
                      <img src="{{ asset('img/icons/middle/indicator-course.svg') }}" alt="PLUS DE POINTS" class="session-indicator-img">
                      {% set registered = countRegistered(course, constant('\\App\\Entity\\Order::STATUS_REGISTERED')) %}
                      {% if registered > 0 %}
                        <div class="session-indicator">{{ registered }}</div>
                      {% endif %}
                    </div>
                  </button>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
      </div>

      <div class="col-lg-6">
        <!-- Contact -->
        <div class="dashboard-block dashboard-contact-block">
          <img src="{{ asset('img/icons/middle/icon-phone.svg') }}" alt="Contact">
          <div class="dashboard-content">
            <div>
              Pour tout problème,<br> n'hésitez pas à nous contacter :
            </div>
            <strong>{{ getParameter('App\\Entity\\Parameter::CODE_PHONE') }}</strong>
          </div>
        </div>

        <!-- Inscription -->
        {% set registered = countAllRegistered(null, constant('\\App\\Entity\\Order::STATUS_REGISTERED'))%}
        <div class="dashboard-block dashboard-inscription-block">
          <img src="{{ asset('img/icons/middle/icon-people.svg') }}" alt="Inscription">
          <div class="dashboard-number">{{ registered }}</div>
          <div class="dashboard-text">
              {{ 'dashboard.inscription'|transchoice(registered)|raw }}
          </div>
        </div>

        <!-- Tarif -->
        {% if app.user.center.tarif.type and ((app.user.center.tarif.type is same as(constant('App\\Entity\\Tarif::TYPE_DATE')) and (app.user.center.tarif.isDiscountDateActive)) or (app.user.center.tarif.type is same as(constant('App\\Entity\\Tarif::TYPE_COURSE')) and app.user.center.tarif.remainingCourse > 0)) %}
          <div class="dashboard-block dashboard-tarif-block">
            <img src="{{ asset('img/icons/middle/icon-dialog.svg') }}" alt="Tarif">
            <div class="dashboard-tarif-content">
              <div class="dashboard-tarif-text">Vous bénéficez actuellement d'un tarif de commission préférentiel :</div>
              <ul class="list-tarif list-unstyled">
                {% if app.user.center.tarif.type is same as(constant('App\\Entity\\Tarif::TYPE_DATE')) and app.user.center.tarif.isDiscountDateActive %}
                  <li>Jusqu'au {{ app.user.center.tarif.endOn|localizeddate('none', 'none', 'fr_FR', null, "cccc dd/MM/yyyy") }} la commission pour tous les stages vendus est {{ app.user.center.tarif.commissionByDate }} €</li>
                {% endif %}
                {% if app.user.center.tarif.type is same as(constant('App\\Entity\\Tarif::TYPE_COURSE')) and app.user.center.tarif.remainingCourse > 0 %}
                  <li>
                    {{ 'dashboard.tarif.nextCourse'|transchoice(app.user.center.tarif.remainingCourse, {
                      '%commission%': app.user.center.tarif.commissionByCourse,
                      '%quantity%': app.user.center.tarif.remainingCourse
                    }) }}
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}