app/symfony/src/Entity/Course.php
<?php

namespace App\Entity;

use App\Entity\Traits\DeletableTrait;
use App\Entity\Traits\IdentifiableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity()
 * @Serializer\ExclusionPolicy("all")
 */
class Course
{
    const TIME_START_AT = '8:00';
    const TIME_START_END = '12:00';
    const TIME_AFTER_AT = '14:00';
    const TIME_AFTER_END = '17:00';

    use IdentifiableTrait;
    use DeletableTrait;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2)
     * @Serializer\Expose()
     */
    protected $amount;

    /**
     * @var Center
     * @ORM\ManyToOne(targetEntity=Center::class, inversedBy="courses")
     */
    protected $center;

    /**
     * @var string
     * @ORM\Column(type="text", nullable=true)
     */
    protected $comment;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $enabled = true;

    /**
     * @var \DateTime
     * @ORM\Column(type="date")
     * @Serializer\Expose()
     */
    protected $endOn;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $endMorningStartAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $endMorningEndAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $endAfternoonStartAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $endAfternoonEndAt;

    /**
     * @var Animator
     * @ORM\ManyToOne(targetEntity=Animator::class)
     */
    protected $former;

    /**
     * @var Order[]
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="course")
     */
    protected $orders;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $originalPrice;

    /**
     * @var Payment
     * @ORM\ManyToOne(targetEntity=Payment::class, inversedBy="courses")
     */
    protected $payment;

    /**
     * @var Place
     * @ORM\ManyToOne(targetEntity=Place::class)
     * @Serializer\Expose()
     */
    protected $place;

    /**
     * @var Animator
     * @ORM\ManyToOne(targetEntity=Animator::class)
     */
    protected $psychologist;

    /**
     * @var int
     * @Assert\Range(min="1", max="20")
     * @ORM\Column(type="integer")
     */
    protected $quantity;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    protected $confirmed = 0;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    protected $registered = 0;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $special = false;

    /**
     * @var \DateTime
     * @ORM\Column(type="date")
     * @Serializer\Expose()
     */
    protected $startOn;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $startMorningStartAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $startMorningEndAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $startAfternoonStartAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="time")
     */
    protected $startAfternoonEndAt;

    public function __construct()
    {
        $this->startMorningStartAt = new \DateTime(self::TIME_START_AT);
        $this->startMorningEndAt = new \DateTime(self::TIME_START_END);
        $this->startAfternoonStartAt = new \DateTime(self::TIME_AFTER_AT);
        $this->startAfternoonEndAt = new \DateTime(self::TIME_AFTER_END);
        $this->endMorningStartAt = new \DateTime(self::TIME_START_AT);
        $this->endMorningEndAt = new \DateTime(self::TIME_START_END);
        $this->endAfternoonStartAt = new \DateTime(self::TIME_AFTER_AT);
        $this->endAfternoonEndAt = new \DateTime(self::TIME_AFTER_END);
        $this->orders = new ArrayCollection();
    }

    /**
     * @return float
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * @param float $amount
     */
    public function setAmount(float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * @return Center
     */
    public function getCenter(): ?Center
    {
        return $this->center;
    }

    /**
     * @param Center $center
     */
    public function setCenter(Center $center): void
    {
        $this->center = $center;
    }

    /**
     * @return string
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     */
    public function setComment(string $comment): void
    {
        $this->comment = $comment;
    }

    /**
     * @return bool
     */
    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     */
    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    /**
     * @return \DateTime|null
     */
    public function getEndOn(): ?\DateTime
    {
        return $this->endOn;
    }

    /**
     * @param \DateTime|null $endOn
     */
    public function setEndOn(?\DateTime $endOn): void
    {
        $this->endOn = $endOn;
    }

    /**
     * @return \DateTime|null
     */
    public function getEndMorningStartAt(): ?\DateTime
    {
        return $this->endMorningStartAt;
    }

    /**
     * @param \DateTime|null $endMorningStartAt
     */
    public function setEndMorningStartAt(?\DateTime $endMorningStartAt): void
    {
        $this->endMorningStartAt = $endMorningStartAt;
    }

    /**
     * @return \DateTime|null
     */
    public function getEndMorningEndAt(): ?\DateTime
    {
        return $this->endMorningEndAt;
    }

    /**
     * @param \DateTime|null $endMorningEndAt
     */
    public function setEndMorningEndAt(?\DateTime $endMorningEndAt): void
    {
        $this->endMorningEndAt = $endMorningEndAt;
    }

    /**
     * @return \DateTime|null
     */
    public function getEndAfternoonStartAt(): ?\DateTime
    {
        return $this->endAfternoonStartAt;
    }

    /**
     * @param \DateTime|null $endAfternoonStartAt
     */
    public function setEndAfternoonStartAt(?\DateTime $endAfternoonStartAt): void
    {
        $this->endAfternoonStartAt = $endAfternoonStartAt;
    }

    /**
     * @return \DateTime|null
     */
    public function getEndAfternoonEndAt(): ?\DateTime
    {
        return $this->endAfternoonEndAt;
    }

    /**
     * @param \DateTime|null $endAfternoonEndAt
     */
    public function setEndAfternoonEndAt(?\DateTime $endAfternoonEndAt): void
    {
        $this->endAfternoonEndAt = $endAfternoonEndAt;
    }

    /**
     * @return Animator
     */
    public function getFormer(): ?Animator
    {
        return $this->former;
    }

    /**
     * @param Animator|null $former
     */
    public function setFormer(?Animator $former): void
    {
        $this->former = $former;
    }

    /**
     * @return Collection
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    /**
     * @return float
     */
    public function getOriginalPrice(): ?float
    {
        return $this->originalPrice;
    }

    /**
     * @param float $originalPrice
     */
    public function setOriginalPrice(?float $originalPrice): void
    {
        $this->originalPrice = $originalPrice;
    }

    /**
     * @return Collection
     */
    public function getConfirmedOrders(): ?Collection
    {
        return $this->orders->filter(function ($order) {
            return Order::STATUS_CONFIRMED === $order->getStatus();
        });
    }

    /**
     * @return Collection
     */
    public function getConfirmedOrdersWithTrainee(): ?Collection
    {
        return $this->orders->filter(function ($order) {
            return Order::STATUS_CONFIRMED === $order->getStatus()
                && null !== $order->getTrainee()->getReference();
        });
    }

    /**
     * @return Collection
     */
    public function getConfirmedOrdersWithTraineeAndRegularCommission(): ?Collection
    {
        return $this->orders->filter(function ($order) {
            return Order::STATUS_CONFIRMED === $order->getStatus()
                && null !== $order->getTrainee()->getReference()
                && false === $order->isReducedCommission();
        });
    }

    /**
     * @return Collection
     */
    public function getConfirmedOrdersWithTraineeAndReducedCommission(): ?Collection
    {
        return $this->orders->filter(function ($order) {
            return Order::STATUS_CONFIRMED === $order->getStatus()
                && null !== $order->getTrainee()->getReference()
                && true === $order->isReducedCommission();
        });
    }

    /**
     * @return float
     */
    public function getCollectedFees(): ?float
    {
        $amount = 0;

        foreach ($this->getConfirmedOrders() as $order) {
            $amount += $order->getCommission();
        }

        return $amount;
    }

    /**
     * @return bool
     */
    public function isSpecial(): bool
    {
        return $this->special;
    }

    /**
     * @param bool $special
     */
    public function setSpecial(bool $special): void
    {
        $this->special = $special;
    }

    /**
     * @return Payment
     */
    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    /**
     * @param Payment $payment
     */
    public function setPayment(Payment $payment): void
    {
        $this->payment = $payment;
    }

    /**
     * @return Place
     */
    public function getPlace(): ?Place
    {
        return $this->place;
    }

    /**
     * @param Place $place
     */
    public function setPlace(Place $place): void
    {

app/symfony/src/Controller/Admin/CourseController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Course;
use EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController;

class CourseController extends EasyAdminController
{
    /**
     * @param object $entity
     */
    protected function persistEntity($entity)
    {
        if (!$entity instanceof Course) {
            return;
        }

        if (!$entity->getCenter()) {
            $entity->setCenter($entity->getPlace()->getCenter());
        }

        parent::persistEntity($entity);
    }
}

app/symfony/src/Controller/Api/CourseController.php
<?php

namespace App\Controller\Api;

use App\Entity\Course;
use App\Manager\CourseManager;
use App\Manager\OrderManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CourseController extends AbstractController
{
    /**
     * @Route(path="/api/course/{id}/purchase", name="api_course_purchase", methods={"PUT"})
     *
     * @param Course       $course
     * @param OrderManager $orderManager
     *
     * @return JsonResponse
     */
    public function purchase(
        Course $course,
        OrderManager $orderManager
    ): JsonResponse {
        $orderManager->clear();
        $orderManager->generate($course);

        return new JsonResponse(null, JsonResponse::HTTP_NO_CONTENT);
    }

    /**
     * @Route(path="/api/course/{id}/enable", name="api_course_enable", methods={"PUT"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\CourseVoter::COURSE_ENABLE'), course)")
     *
     * @param Course        $course
     * @param CourseManager $courseManager
     *
     * @return JsonResponse
     */
    public function enable(Course $course, CourseManager $courseManager): JsonResponse
    {
        $courseManager->enable($course);

        return new JsonResponse(null, JsonResponse::HTTP_NO_CONTENT);
    }

    /**
     * @Route(path="/api/course/{id}/disable", name="api_course_disable", methods={"PUT"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\CourseVoter::COURSE_DISABLE'), course)")
     *
     * @param Course        $course
     * @param CourseManager $courseManager
     *
     * @return JsonResponse
     */
    public function disable(Course $course, CourseManager $courseManager): JsonResponse
    {
        $courseManager->disable($course);

        return new JsonResponse(null, JsonResponse::HTTP_NO_CONTENT);
    }

    /**
     * @Route(path="/api/course/{id}/orders", name="api_course_orders", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\CourseVoter::COURSE_VIEW'), course)")
     *
     * @param Course       $course
     * @param OrderManager $orderManager
     *
     * @return Response
     */
    public function orders(Course $course, OrderManager $orderManager): Response
    {
        return $this->render('middle/course/registered.html.twig', [
            'orders' => $orderManager->getRegisteredByCourse($course),
        ]);
    }

    /**
     * @Route(path="/api/courses", name="api_courses", methods={"POST"})
     *
     * @param CourseManager $courseManager
     * @param Request       $request
     *
     * @return Response
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function cheapest(CourseManager $courseManager, Request $request): Response
    {
        return $this->render('front/course/cheapest.html.twig', [
            'courses' => $courseManager->getCarouselCourses(
                $request->get('lat'),
                $request->get('lng'),
                (bool) $request->get('geolocated')
            ),
        ]);
    }
}

app/symfony/src/Controller/CourseController.php
<?php

namespace App\Controller;

use App\Entity\Course;
use App\Form\SearchType;
use App\Manager\CourseManager;
use App\Repository\CourseRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CourseController extends AbstractController
{
    /**
     * @Route(path="/search", name="course_search", methods={"GET"})
     *
     * @param CourseManager    $courseManager
     * @param CourseRepository $courseRepository
     * @param Request          $request
     *
     * @return Response
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function search(
        CourseManager $courseManager,
        CourseRepository $courseRepository,
        Request $request
    ): Response {
        $form = $this->createForm(SearchType::class, null, ['advanced' => true]);
        $form->handleRequest($request);

        $courses = $courseManager->search($form);

        return $this->render('front/course/search.html.twig', [
            'form' => $form->createView(),
            'courses' => $courses,
        ]);
    }
}

app/symfony/src/Controller/Middle/AccountingController.php
<?php

namespace App\Controller\Middle;

use App\Entity\Center;
use App\Services\ReportingService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;

class AccountingController extends AbstractController
{
    /**
     * @Route(path="/cssr/accounting", name="middle_accounting_list", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_VIEW'))")
     *
     * @return Response
     */
    public function list(): Response
    {
        return $this->render('middle/accounting/list.html.twig');
    }

    /**
     * @Route(path="/cssr/accounting/fee", name="middle_accounting_fee", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_FEE'))")
     *
     * @param ReportingService $reportingService
     * @param Center|null      $center
     *
     * @return StreamedResponse
     */
    public function fee(ReportingService $reportingService): Response
    {
        return $reportingService->exportApplicationFee();
    }

    /**
     * @Route(path="/cssr/accounting/refund", name="middle_accounting_refund", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_REFUND'))")
     *
     * @param ReportingService $reportingService
     * @param Center           $center
     *
     * @return StreamedResponse
     */
    public function refund(ReportingService $reportingService): Response
    {
        return $reportingService->exportOrderRefund();
    }

    /**
     * @Route(path="/cssr/accounting/banking", name="middle_accounting_banking", methods={"GET"})
     * @Security("is_granted(constant('\\App\\Security\\Voter\\AccountingVoter::ACCOUNTING_BANKING'))")
     *
     * @param ReportingService $reportingService
     *
     * @return Response
     */
    public function banking(ReportingService $reportingService): Response
    {
        $export = $reportingService->getExportBankZip();

        $response = new Response(file_get_contents($export));
        $response->headers->set('Content-Type', 'text/csv; charset=windows-1252');
        $response->headers->set('Content-Type', 'application/zip');
        $response->headers->set('Content-Disposition', 'attachment;filename="'.$export.'"');
        $response->headers->set('Content-length', filesize($export));

        unlink($export);

        return $response;
    }
}

app/symfony/templates/middle/course/edit.html.twig
{% extends 'middle/base.html.twig' %}

{% block body %}
<div class="detail-stage-wrap  ">
  <div class="middle-title-section">
    <h1 class="middle-default-title">
        {% if course.id != null %}
            {{ 'info.stage.titleEdit'|trans }}
        {% else %}
            {{ 'info.stage.titleAdd'|trans }}
        {% endif %}
    </h1>
  </div>
  {{ form_start(form) }}
    <div class="add-stage-block">
      <h2 class="middle-default-alt-title">{{ 'info.stage.edit.info'|trans }}</h2>
      <div class="row">
        <div class="col-sm-4">
          {{ form_row(form.place) }}
        </div>
        <div class="col-sm-4">
          {{ form_row(form.psychologist) }}
        </div>
        <div class="col-sm-4">
          {{ form_row(form.former) }}
        </div>
      </div>
    </div>

    <div class="add-stage-block">
      <h2 class="middle-default-alt-title">{{ 'info.stage.edit.dateHoraire'|trans }}</h2>
      <div class="row">
        <div class="col-sm-4">
          {{ form_row(form.startOn) }}
        </div>
        <div class="col-sm-4 col-hour">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.startMorningStartAt) }}
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.startMorningEndAt) }}
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-4 col-hour">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.startAfternoonStartAt) }}
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.startAfternoonEndAt) }}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          {{ form_row(form.endOn) }}
        </div>
        <div class="col-sm-4 col-hour">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.endMorningStartAt) }}
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.endMorningEndAt) }}
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-4 col-hour">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.endAfternoonStartAt) }}
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                {{ form_row(form.endAfternoonEndAt) }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="add-stage-block add-stage-sp-block">
      <div class="row">
        <div class="col-sm-2">
          <div class="form-group ">
            <label class="control-label">{{ 'info.stage.edit.stageSpecifique'|trans }}:</label>
            {{ form_row(form.special) }}
          </div>
        </div>
        <div class="col col-quantity">
          {{ form_row(form.quantity) }}
        </div>
        <div class="col">
          <div class="form-group-price">
            {{ form_row(form.amount) }}
          </div>
        </div>
        {% if course.place.department is defined %}
          {% set minPrice = getMinPriceByDepartment(course.place.department) %}
        {% endif %}
        <div class="col">
          <div class="form-group-price" id="min-price" {% if minPrice is not defined %}style="display: none;"{% endif %}>
            <div class="form-group">
              <label for="">{{ 'info.stage.edit.prix'|trans }}:</label>
              <input type="number" class="form-control" value="{% if minPrice is defined %}{{ minPrice }}{% endif %}" readonly>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% if is_granted('ROLE_SMP') or is_granted('ROLE_CONSULTANT') %}
        <br> <div class="participants-comment-block">
            <div class="form-group">
                <label class="middle-default-alt-title">Commentaire :</label>
                <div class="detail-comment-text">{{ form_widget(form.comment) }}</div>
            </div>
        </div>
    {% endif %}

    <div class="add-stage-action-block">
      {{ form_row(form.submit) }}
    </div>
  {{ form_end(form) }}
</div>
{% endblock %}

app/symfony/templates/middle/course/index.html.twig
{% extends 'middle/base.html.twig' %}

{% block body %}
    <div class="detail-stage-wrap  ">
        <div class="middle-title-section">
            <h1 class="middle-default-title">{{ 'info.stage.titleDetail'|trans }}</h1>
            <div class="head-action-block">
                <ul class="list-middle-link list-inline">
                    <li class="list-inline-item"><a href="{{ path('middle_course_emargement', { 'id': course.id }) }}" target="_blank">{{ 'info.stage.feuilleEmargement'|trans }}</a></li>
                    <li class="list-inline-item"><a href="{{ path('middle_order_attestation', { 'id': course.id }) }}" target="_blank">{{ 'info.stage.editAttestation'|trans }}</a></li>
                </ul>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-4">
                    <div class="detail-stage-block">
                        <ul class="list-info-default list-unstyled">
                            <li>
                                <div class="info-label">{{ 'info.stage.table.firstDay'|trans }} :</div>
                                <div class="info-detail">{{ course.startOn|date('d/m/Y') }}</div>
                            </li>
                            <li>
                                <div class="info-label">{{ 'info.stage.table.lieu'|trans }} :</div>
                                <div class="info-detail">{{ course.place.address }}</div>
                            </li>
                            <li>
                                <div class="info-label">{{ 'info.stage.table.psychologue'|trans }} :</div>
                                <div class="info-detail">{{ course.psychologist }}</div>
                            </li>
                            <li>
                                <div class="info-label">{{ 'info.stage.table.bAFM_BAFCRI'|trans }} :</div>
                                <div class="info-detail">{{ course.former }}</div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-8">
                    <div class="participants-block">
                        {% if course.confirmedOrders|length %}
                            <div class="participants-title-block">
                                <h3 class="participants-title">{{ 'info.stage.listParticipant'|trans }}:</h3>
                                {% if is_granted(constant('\\App\\Security\\Voter\\CourseVoter::COURSE_REGISTER'), course) %}
                                    <a href="{{ path('middle_course_register', { id: course.id }) }}" class="btn btn-secondary btn-sm">{{ 'info.stage.addStagiaire'|trans }}</a>
                                {% endif %}
                            </div>
                        {% else %}
                          <div class="participants-title-block">
                              <h3 class="participants-title">{{ 'info.stage.listParticipantEmpty'|trans }}</h3>
                          </div>
                        {% endif %}

                        <div class="list-participants row">
                          {% for order in course.confirmedOrders %}
                              <div class="col col-6">
                                  <a href="{{ path('middle_order', {'id': order.id}) }}" class="participants-item">
                                      <div class="participants-name">{{ order.trainee.firstName }}</div>
                                  </a>
                              </div>
                          {% endfor %}
                        </div>
                    </div>
                    <br>
                    {% if is_granted('ROLE_SMP') or is_granted('ROLE_CONSULTANT') %}
                        <div class="participants-comment-block">
                            {{ form_start(form) }}
                                <div class="form-group">
                                    <label class="middle-default-alt-title">Commentaire :</label>
                                    <div class="detail-comment-text">{{ form_widget(form.comment) }}</div>
                                </div>
                            {{ form_end(form) }}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/symfony/templates/middle/course/registered.html.twig
{% for order in orders %}
    <tr data-order-id="{{ order.id }}">
        <td>{{ order.trainee.lastName }} {{ order.trainee.firstName }}</td>
        <td>
            <div class="icon-dot sub-pre-order-id" data-url-order-id="{{ order.id }}"></div>
        </td>
        {% if is_granted(constant('\\App\\Security\\Voter\\OrderVoter::ORDER_CONFIRM'), order) %}
            <td>
                <button type="button" class="btn btn-primary btn-full" data-url-confirm="{{ path('api_order_confirm', {'id': order.id }) }}">
                    <i class="icon-check"></i>
                    <span class="sr-only">Accepter</span>
                </button>
            </td>
        {% endif %}
        {% if is_granted(constant('\\App\\Security\\Voter\\OrderVoter::ORDER_TRANSFER'), order) %}
            <td>
                <button type="button" class="btn btn-primary btn-full" data-url-transfer="{{ path('api_order_transfer', {'id': order.id }) }}">
                    <i class="icon-d-arrow"></i>
                    <span class="sr-only">Transférer</span>
                </button>
            </td>
        {% endif %}
        {% if is_granted(constant('\\App\\Security\\Voter\\OrderVoter::ORDER_WAIT'), order) %}
            <td>
                <button type="button" class="btn btn-primary btn-full" data-url-wait="{{ path('api_order_wait', {'id': order.id }) }}">
                    <i class="icon-time"></i>
                    <span class="sr-only">En attente</span>
                </button>
            </td>
        {% endif %}
        {% if is_granted(constant('\\App\\Security\\Voter\\OrderVoter::ORDER_REFUND'), order) %}
            <td>
                <button type="button" class="btn btn-primary btn-full" data-url-order="{{ path('api_order_view', { 'id': order.id }) }}" data-url-refund="{{ path('api_order_refund', {'id': order.id }) }}">
                    <i class="icon-m-rem"></i>
                    <span class="sr-only">Remboursement</span>
                </button>
            </td>
        {% endif %}
        {% if is_granted(constant('\\App\\Security\\Voter\\OrderVoter::ORDER_CANCEL'), order) %}
            <td>
                <button type="button" class="btn btn-primary btn-full" data-url-cancel="{{ path('api_order_cancel', {'id': order.id }) }}">
                    <i class="icon-close"></i>
                    <span class="sr-only">Annuler</span>
                </button>
            </td>
        {% endif %}
    </tr>
{% endfor %}